EN_ESPERA = 0
EN_CURSO = 1
PUNTOS_OBJETIVO = (('15', "15"), ('30', "30"))
CARTAS_JUGADOR = 3

#ESTADO DE CANTO
NO_CONTESTADO = -1
ACEPTADO = 0
RECHAZADO = 1

#OPCIONES DE JUEGO
QUIERO = 0
NO_QUIERO = 1
TRUCO = 2
RETRUCO = 3
VALE_CUATRO = 4
ENVIDO = 5
DOBLE_ENVIDO = 6
REAL_ENVIDO = 7
FALTA_ENVIDO = 8
IRSE_AL_MAZO = 9
SON_BUENAS = 10
SIGUIENTE_RONDA = 11
PEDIR_PUNTOS = 12
MOSTRAR_PUNTOS = 13

OPCIONES = {
    QUIERO: "QUIERO",
    NO_QUIERO: "NO QUIERO",
    TRUCO: "TRUCO",
    RETRUCO: "RETRUCO",
    VALE_CUATRO: "VALE CUATRO",
    ENVIDO: "ENVIDO",
    DOBLE_ENVIDO: "ENVIDO",
    REAL_ENVIDO: "REAL ENVIDO",
    FALTA_ENVIDO: "FALTA ENVIDO",
    IRSE_AL_MAZO: "IRSE AL MAZO",
    SON_BUENAS: "SON BUENAS",
    SIGUIENTE_RONDA: "SIGUIENTE RONDA",
    PEDIR_PUNTOS: "PEDIR PUNTOS",
    MOSTRAR_PUNTOS: "MOSTRAR PUNTOS"
}

PTS_CANTO = {
    TRUCO: 1,
    ENVIDO: 1,
}
