EN_ESPERA = 0
EN_CURSO = 1
PUNTOS_OBJETIVO = (('15',"15"),('30',"30"))
CARTAS_JUGADOR = 3



#ESTADO DE CANTO
NO_CONTESTADO = -1
ACEPTADO = 0
RECHAZADO = 1

#OPCIONES DE JUEGO

QUIERO = 0
NO_QUIERO = 1
TRUCO = 2
ENVIDO = 3
IRSE_AL_MAZO = 4
SON_BUENAS = 5
SIGUIENTE_RONDA = 6
PEDIR_PUNTOS = 7
MOSTRAR_PUNTOS = 8

OPCIONES={
    QUIERO : "QUIERO",
    NO_QUIERO : "NO QUIERO",
    TRUCO : "TRUCO",
    ENVIDO : "ENVIDO",
    IRSE_AL_MAZO : "IRSE AL MAZO",
    SON_BUENAS : "SON BUENAS",
    SIGUIENTE_RONDA : "SIGUIENTE RONDA",
    PEDIR_PUNTOS : "PEDIR PUNTOS",
    MOSTRAR_PUNTOS : "MOSTRAR PUNTOS"
}

PTS_CANTO={
    TRUCO : 1,
    ENVIDO : 1,
}
